name: Build and Release

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # скачиваем ресурсы с облака
      - name: Download resources
        uses: ./.github/actions/download-resources
        with:
          folder-url: https://drive.google.com/drive/folders/1xlyLjaAZCGDY4fByLub-mwF4EIwDijip?usp=drive_link
          output-dir: test_template\Resources

      - name: Setup build tools
        uses: ./.github/actions/setup-build-tools

      - name: Read version
        id: version
        uses: ./.github/actions/read-version

      - name: Build installer
        id: build
        uses: ./.github/actions/build-installer

      - name: Publish release
        uses: ./.github/actions/publish-release
        with:
          tag: ${{ steps.version.outputs.tag }}
          title: Project1 ${{ steps.version.outputs.version }}
          asset: ${{ steps.build.outputs.msi-path }}
          token: ${{ github.token }}
